# Generated by Django 5.2.1 on 2025-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieceName', models.CharField(max_length=255)),
                ('artistName', models.CharField(max_length=255)),
                ('preview', models.ImageField(upload_to='previews/')),
            ],
        ),
    ]
