# Generated by Django 5.2.1 on 2025-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='preview',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
