# Generated by Django 5.2.1 on 2025-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='preview',
            field=models.ImageField(upload_to='previews/'),
        ),
    ]
