# Generated by Django 5.2.1 on 2025-06-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_price_alter_auction_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
