# Generated by Django 5.2.1 on 2025-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_auction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='condition',
            field=models.CharField(default='Minimal Damage', max_length=255),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.CharField(default='None', max_length=1023),
            preserve_default=False,
        ),
    ]
