# Generated by Django 5.2.1 on 2025-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_condition_auction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='price',
            new_name='priceBIN',
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(default='No Description', max_length=1023),
        ),
    ]
