# Generated by Django 5.2.1 on 2025-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
