# Generated by Django 5.2.1 on 2025-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_auction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
