# Generated by Django 5.2.1 on 2025-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highestBid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
