# Generated by Django 5.2.1 on 2025-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_alter_auction_highestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='highestBid',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
