# Generated by Django 5.2.1 on 2025-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_alter_auction_highestbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='type',
            field=models.CharField(default='Type Unavailable', max_length=1023),
        ),
    ]
