# Generated by Django 5.2.1 on 2025-06-07 15:06

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auction_type'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='type',
        ),
        migrations.AddField(
            model_name='auction',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
