# Generated by Django 5.2.1 on 2025-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_remove_auction_type_auction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='highestBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
