# Generated by Django 5.2.1 on 2025-06-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_alter_auction_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='sold_for',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
