# Generated by Django 5.2.1 on 2025-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_auction_end_time_auction_sold_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='sold_for',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
